# Generated by Django 4.1 on 2022-09-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000000)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('other_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_img')),
                ('city', models.CharField(max_length=100)),
                ('title', models.TextField(blank=True, null=True)),
                ('middlename', models.TextField(blank=True, null=True)),
                ('adreess', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, verbose_name='Biography (Age, Language, Location...)')),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
