# Generated by Django 4.1 on 2022-09-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='available',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='checkings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='savings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
