# Generated by Django 4.1 on 2022-09-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novaapp', '0002_data_available_data_checkings_data_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='first_his',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='last_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='second_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='third_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
